# Generated by Django 5.2.16 on 2026-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='reply_text',
            field=models.TextField(blank=True),
        ),
    ]
