# Generated by Django 5.2.16 on 2026-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('gallery', 'Gallery'), ('artists', 'Artists'), ('services', 'Services'), ('about', 'About'), ('booking', 'Booking'), ('support', 'Support'), ('contact', 'Contact'), ('auth', 'Auth')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
