# Generated by Django 5.2.16 on 2026-07-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('gallery', 'Gallery'), ('artists', 'Artists'), ('services', 'Services'), ('about', 'About'), ('booking', 'Booking'), ('support', 'Support'), ('contact', 'Contact'), ('newsletter', 'Newsletter'), ('auth', 'Auth')], max_length=20),
        ),
    ]
