# Generated by Django 5.2.16 on 2026-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='+91', max_length=8)),
                ('phone', models.CharField(max_length=20)),
                ('appointment_type', models.CharField(choices=[('Studio Service', 'Studio Service'), ('Home Service', 'Home Service')], default='Studio Service', max_length=20)),
                ('party_size', models.CharField(default='Single (1 person)', max_length=60)),
                ('location', models.CharField(max_length=160)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='URLs returned by /api/uploads/images/')),
                ('travel_fee', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('google_calendar_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('calendar_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('travel_fee', models.PositiveIntegerField(default=0, help_text='0 = free (Law Gate / Phagwara / Jalandhar)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
